lomba/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "lomba"

urlpatterns = [
    path('', views.lomba_list, name='lomba_list'),
    path('<str:alias>/', views.lomba_detail, name='lomba_detail')
]

mtqui/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('gallery/', include('gallery.urls')),
    path('auth/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('seminar/', include('seminar.urls')),
    path('lomba/', include('lomba.urls')),
    path('admin_mtqui/', include('admin_mtqui.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler400 = "homepage.views.bad_request_view"
handler403 = "homepage.views.permission_denied_view"
handler404 = "homepage.views.page_not_found_view"
handler500 = "homepage.views.server_error_view"

seminar/urls.py
from django.urls import path
from .views import seminarlanding, getseminar, getseminarform

app_name = "seminar"

urlpatterns = [
    path('', seminarlanding, name='seminar_landing'),
    path('more/<str:id_seminar>/', getseminar, name='get_seminar'),
    path('enroll/', getseminarform, name='get_seminar_form'),
]

seminar/models.py
from django.db import models

# Create your models here.
class GuestStars(models.Model):
    nama = models.CharField(max_length=150)
    biografi = models.TextField(default="test")

    def __str__(self):
        return self.nama

class Seminar(models.Model):
    judul_seminar = models.CharField(max_length=200)
    about = models.CharField(max_length=300)
    guest_stars = models.ManyToManyField(GuestStars)
    subjects = models.TextField()
    d_day = models.DateTimeField()
    end_time = models.DateTimeField()
    seminar_image = models.ImageField(default='1955361.jpg')
    is_past = models.BooleanField(default=False)
    air_time = models.CharField(null=True, blank=True, max_length=300)

    def __str__(self):
        return self.judul_seminar

seminar/views.py
from django.shortcuts import render, get_object_or_404
from .models import Seminar
from django.utils import timezone
import random


# Create your views here.


def seminarlanding(request):
    semua_seminar = Seminar.objects.all().order_by('d_day')

    id_list = []
    random_seminar = []
    past_empty = False
    future_empty = False
    counter = 0

    for seminar in semua_seminar:
        id_list.append(seminar.id)

    # Get 4 or less random seminar
    if (Seminar.objects.count() < 4):
        randomized_seminar = random.sample(id_list, Seminar.objects.count())
    else:
        randomized_seminar = random.sample(id_list, 4)

    # For each carousel seminar, get its air time and check if past or not
    for i in randomized_seminar:
        temp_seminar = Seminar.objects.get(id=i)

        if temp_seminar.d_day < timezone.localtime():
            temp_seminar.is_past = True

        random_seminar.append(temp_seminar)

    for seminar in semua_seminar:
        if seminar.d_day < timezone.localtime():
            seminar.is_past = True
            counter += 1

    if counter == semua_seminar.count():
        future_empty = True
    elif counter == 0:
        past_empty = True

    argument = {
        'seminar_list': semua_seminar,
        'carousel_seminar': random_seminar,
        'future_empty': future_empty,
        'past_empty': past_empty
    }

    return render(request, 'seminar_landing.html', argument)


def getseminar(request, id_seminar):
    seminar = get_object_or_404(Seminar, id=id_seminar)

    all_biografi = []

    guest_stars = seminar.guest_stars.all()
    all_subjects = [x for x in seminar.subjects.split(';') if x]

    if(guest_stars.first().biografi != 'test'):
        all_biografi = [x for x in guest_stars.first().biografi.split(';') if x]

    if seminar.d_day < timezone.localtime():
        seminar.is_past = True

    argument = {
        'seminar': seminar,
        'guest_stars': guest_stars,
        'all_subjects': all_subjects,
        'all_biografi': all_biografi
    }
    return render(request, 'each_seminar.html', argument)




def getseminarform(request):
    return render(request, 'form_template.html')

seminar/templates/each_seminar.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    {{ seminar.judul_seminar }}
{% endblock %}

{% block head %}
     <!-- My CSS-->
    <link rel="stylesheet" href="{% static 'css/seminar.css' %}">
{% endblock %}


{% block content %}
    <div class="kenta-head">
        <div class="kenta-head-content">
            <div>
                {% if not seminar.is_past %}
                <span class="kenta-blurlable"><span class="dot mr-1"></span> AIRING IN: {{ seminar.d_day|date:"d M Y" }}, {{ seminar.d_day|date:'G:i' }} - {{ seminar.end_time|date:'G:i' }} WIB</span>
                {% else %}
                <span class="kenta-blurlable"><span class="dot2 mr-1"></span> AIRED IN: {{ seminar.d_day }} </span>
                {% endif %}
                <h2 style="font-weight: 700">{{ seminar.judul_seminar }}</h2>
                <h4 style="margin-bottom: 0">Musabaqah Tilawatil Quran</h4> <h4 style="font-weight: bold; font-style: italic">Universitas Indonesia</h4>
            </div>
        </div>
        <div class="kenta-head-img"
             style="background-image: url('{{ seminar.seminar_image.url }}')">
        </div>
    </div>


    <div class="info_container" style="padding: 6.5em">
    <ul class="list-group list-group-flush">
    <li class="list-group-item">
        <h4>About</h4>
        <p style="width: 60%" class="about">{{ seminar.about }}</p>
    </li>
    <li class="list-group-item">
        <h4>Speakers</h4>
        <ul class="guest_stars">
            {% for guest_star in guest_stars %}
                <li>{{ guest_star.nama }}</li>
            {% endfor %}
        </ul>
    </li>

    {% if all_biografi|length > 0 %}
    <li class="list-group-item">
        <h4>Achievement</h4>
        <ul class="guest_stars">
            {% for biografi in all_biografi %}
                <li>{{ biografi }}</li>
            {% endfor %}
        </ul>
    </li>
    {% endif %}

    <li class="list-group-item">
        <h4>We’ll be talking about...</h4>
        <ul class="subjects">
            {% for subject in all_subjects %}
                <li>{{ subject }}</li>
            {% endfor %}
        </ul>
    </li>

    <li class="list-group-item" style="display:flex; justify-content: center;align-items: center; flex-direction: column">
        <p style="margin: 5px">Interested?</p>
        {% if not seminar.is_past %}
        <a href="{% url 'seminar:get_seminar_form' %}"><button class="btn btn-primary">ENROLL NOW!</button></a>
        {% else %}
        <button class="btn btn-primary" disabled>ENROLL NOW!</button>
        {% endif %}

    </li>

    </ul>

    </div>

{% endblock %}

seminar/templates/form_template.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
   Form Pendaftaran Workshop
{% endblock %}

{% block head %}
     <!-- My CSS-->
    <link rel="stylesheet" href="{% static 'css/seminar.css' %}">
{% endblock %}

{% block content %}

    <div class="kenta-head">
        <div class="kenta-head-content">
            <div>
                <span class="kenta-blurlable max_content_behavior">Pendaftaran Workshop</span>
                <h2 style="font-weight: 700; font-size: 40px">WORKSHOP MTQ UI</h2>
                <h3 style="margin-bottom: 0px">Musabaqah Tilawatil Quran</h3> <h3 style="font-weight: bold; font-style: italic">Universitas Indonesia</h3>
            </div>
        </div>
        <div class="kenta-head-img"
             style="background-image: url('{% static 'img/quran.svg' %}')">
        </div>
    </div>


    <div class="container" id="ff-compose" style="margin-top: 13vh; margin-bottom: 13vh"></div>
    <script async defer src="https://formfacade.com/include/114999475763209462002/form/1FAIpQLSdDlCsJqX0IX_z5UeSbA8HnyzRqYstRHGgAKMeIWPUuzq9xWg/bootstrap.js?div=ff-compose"></script>
{% endblock %}

seminar/templates/seminar_landing.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Seminar
{% endblock %}

{% block head %}
     <!-- My CSS-->
    <link rel="stylesheet" href="{% static 'css/seminar.css' %}">
    <script src="{% static 'js/seminar.js' %}"></script>

{% endblock %}

{% block content %}

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">

      {% for each_seminar in carousel_seminar %}
          <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}" id="circle" style="list-style: none"></li>
      {% endfor %}
  </ol>
  <div class="carousel-inner">
  {% for each_seminar in carousel_seminar %}
      <div class="carousel-item">
        <div class="kenta-head">
        <div class="kenta-head-content">
            <div>
                {% if not each_seminar.is_past %}
                 <span class="kenta-blurlable"><span class="dot mr-1"></span> AIRING IN: {{ each_seminar.d_day|date:"d M Y" }}, {{ each_seminar.d_day|date:'G:i' }} - {{ each_seminar.end_time|date:'G:i' }} WIB </span>
                {% else %}
                <span class="kenta-blurlable"><span class="dot2 mr-1"></span> AIRED IN: {{ each_seminar.d_day|date:"d M Y" }}, {{ each_seminar.d_day|date:'G:i' }} - {{ each_seminar.end_time|date:'G:i' }} WIB </span>
                {% endif %}
                <h2 style="font-weight: 700">{{ each_seminar.judul_seminar }}</h2>
                <h5 id="tema">{{ each_seminar.about }}</h5>
            <a href="{% url 'seminar:get_seminar' each_seminar.id %}"><button class="btn btn-light" style="width: 150px" id="know_more_car">Know More!</button></a>
            </div>
        </div>
        <div class="kenta-head-img"
             style="background-image: url('{{ each_seminar.seminar_image.url }}')">
        </div>
        </div>
    </div>

  {% endfor %}
  </div>

      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev" style="width: 4.5%;">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next" style="width: 4.5%;">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

    {% if not future_empty %}
    <div class="upcoming_container">
    <h2 style="font-weight: bold"> Upcoming Seminar </h2>
    <div class="card_container">
        {% for seminar in seminar_list %}
        {% if not seminar.is_past %}
            <div class="card seminar_card">
                <img class="card-img-top img-fluid" style="object-fit: cover; height: 250px" src="{{ seminar.seminar_image.url }}" alt="">

                <div class="judul_seminar_cont">
                    <p>{{ seminar.judul_seminar }}</p>
                    <div class="know_more">
                        <a href="{% url 'seminar:get_seminar' seminar.id %}"><p style="font-size: 12px; font-weight: 500; padding: 3px;">Know More!</p></a></div>
                </div>

            </div>
        {% endif%}
        {% endfor %}
    </div>
    </div>
    {% endif %}

    {% if not past_empty %}
    <div class="past_seminar" >
    <h2 style="font-weight: bold"> Past Seminar </h2>
      <div class="card_container">
         {% for seminar in seminar_list %}

        {% if seminar.is_past %}
            <div class="card seminar_card">
                <img class="img-fluid" style="object-fit: cover; height: 250px" src="{{ seminar.seminar_image.url }}" alt="">

                <div class="judul_seminar_cont">
                    <p>{{ seminar.judul_seminar }}</p>
                    <div class="know_more">
                        <a href="{% url 'seminar:get_seminar' seminar.id %}"><p style="font-size: 12px; font-weight: 500; padding: 3px;">Know More!</p></a>
                    </div>
                </div>

            </div>
        {% endif %}
        {% endfor %}
    </div>
    </div>
    {% endif %}

    <script>
        $(document).ready(function(){
            $(".carousel-item:first").addClass("active")
            $("#circle:first").addClass("active")
        });
    </script>

{% endblock %}