dashboard/urls.py
from django.urls import path
from dashboard.views import *

app_name = 'dashboard'

urlpatterns = [
    path('', home, name='home'),
    path('enroll/<int:id_kompetisi>', enroll, name='enroll'),
    path('add/<int:id_kelompok>', add_anggota, name='add_anggota'),
    path('edit/participant/<int:id_peserta>', edit_peserta, name='edit_peserta'),
    path('edit/team/<int:id_kelompok>', edit_kelompok, name='edit_kelompok'),
    path('edit/member/<int:id_anggota>', edit_anggota, name='edit_anggota'),
    path('delete/participant/<int:id_peserta>', delete_peserta, name='delete_peserta'),
    path('delete/team/<int:id_kelompok>', delete_kelompok, name='delete_kelompok'),
    path('delete/member/<int:id_anggota>', delete_anggota, name='delete_anggota'),
    path('view/<int:id_kompetisi>', view_enrollments, name='view_enrollments'),
    path('view/team/<int:id_kelompok>', view_kelompok, name='view_kelompok'),
]

lomba/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "lomba"

urlpatterns = [
    path('', views.lomba_list, name='lomba_list'),
    path('<str:alias>/', views.lomba_detail, name='lomba_detail')
]

mtqui/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('gallery/', include('gallery.urls')),
    path('auth/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('seminar/', include('seminar.urls')),
    path('lomba/', include('lomba.urls')),
    path('admin_mtqui/', include('admin_mtqui.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler400 = "homepage.views.bad_request_view"
handler403 = "homepage.views.permission_denied_view"
handler404 = "homepage.views.page_not_found_view"
handler500 = "homepage.views.server_error_view"

lomba/models.py
from django.db import models

class Mentor(models.Model):
    nama_mentor = models.CharField(max_length=100)

    def __str__(self):
        return self.nama_mentor

class Lomba(models.Model):
    nama_lomba = models.CharField(max_length=100)
    alias = models.CharField(max_length=20)
    image = models.ImageField(null=True, blank=True)
    image_url = models.TextField(null=True, blank=True, default='https://images.unsplash.com/photo-1519818187420-8e49de7adeef')
    about = models.TextField()
    start_date = models.DateField(null=True, blank=True)
    finish_date = models.DateField(null=True, blank=True)
    guidebook_link = models.CharField(max_length=200, default='/guidebook')
    nama_mentor = models.ManyToManyField(Mentor, null=True, blank=True)
    custom_timeline = models.BooleanField(default=False)

    def __str__(self):
        return self.nama_lomba

class LombaRule(models.Model):
    nama_lomba = models.ForeignKey(Lomba, on_delete=models.CASCADE)
    rule = models.TextField()

    def __str__(self):
        return "%s -> LombaRule: %s" % (str(self.nama_lomba), self.rule)

class ParticipantRequirement(models.Model):
    nama_lomba = models.ForeignKey(Lomba, on_delete=models.CASCADE)
    requirement = models.TextField()

    def __str__(self):
        return "%s -> ParticipantRequirement: %s" % (str(self.nama_lomba), self.requirement)

class TrainingLearnt(models.Model):
    nama_lomba = models.ForeignKey(Lomba, on_delete=models.CASCADE)
    learnt = models.TextField()

    def __str__(self):
        return "%s -> TrainingLearnt: %s" % (str(self.nama_lomba), self.learnt)

class TrainingTimeline(models.Model):
    nama_lomba = models.ForeignKey(Lomba, on_delete=models.CASCADE)
    start_date = models.DateField()
    finish_date = models.DateField()
    active = models.BooleanField(null=True, blank=True, default=False)
    deskripsi = models.CharField(max_length=100)

    def __str__(self):
        return "%s -> TrainingTimeline: %s - %s -> %s" % (str(self.nama_lomba), str(self.start_date), str(self.finish_date), self.deskripsi)

lomba/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import *
import datetime, random

def cek_timeline(lomba, trainingTL):
    if not lomba.custom_timeline:
        today = datetime.date.today()
        for item in trainingTL:
            if item.start_date <= today <= item.finish_date:
                trainingTL.filter(id=item.id).update(active=True)
            elif item.start_date > today:
                trainingTL.filter(id=item.id).update(active=None)

            if item.finish_date < today:
                trainingTL.filter(id=item.id).update(active=False)

def cek_timeline_past(trainingTL):
    pastTL = []
    for item in trainingTL:
        if (item.active is not None) and (not item.active):
            pastTL.append(item)

    return pastTL


def lomba_list(request):
    lombaList = Lomba.objects.all()
    timeline = TrainingTimeline.objects.all()

    for lomba in lombaList:
        trainingTL = TrainingTimeline.objects.filter(nama_lomba=lomba)
        cek_timeline(lomba, trainingTL)
        cek_timeline_past(trainingTL)

    alias_list = []
    for lomba in lombaList:
        alias_list.append(lomba.alias)

    if Lomba.objects.count() < 4:
        lomba_random = random.sample(alias_list, Lomba.objects.count())
    else:
        lomba_random = random.sample(alias_list, 4)

    carousel_lomba = []
    for lomba in lombaList:
        for item in lomba_random:
            if lomba.alias == item:
                carousel_lomba.append(lomba)

    tlList = dict.fromkeys(lombaList)
    for k in tlList.keys():
        temp = timeline.filter(nama_lomba=k)
        for item in temp:
            if item.active:
                tlList[k] = item

    today = datetime.date.today()
    active = dict.fromkeys(lombaList)
    for k in active.keys():
        temp = timeline.filter(nama_lomba=k)
        if temp.exists():
            if temp.first().start_date <= today <= temp.latest('finish_date').finish_date:
                active[k] = temp.latest('finish_date')

    args = {
        'carousel_lomba': carousel_lomba,
        'lombaList': lombaList,
        'timeline': timeline,
        'active': active,
        'tlList': tlList
    }

    return render(request, "lomba.html", args)

def lomba_detail(request, alias):
    lomba = get_object_or_404(Lomba, alias=alias)
    rules = LombaRule.objects.filter(nama_lomba=lomba)
    requirement = ParticipantRequirement.objects.filter(nama_lomba=lomba)
    learnt = TrainingLearnt.objects.filter(nama_lomba=lomba)
    trainingTL = TrainingTimeline.objects.filter(nama_lomba=lomba)

    trainingTL = trainingTL.all().order_by('start_date', 'finish_date')
    mentors = lomba.nama_mentor.all()
    isLoggedIn = False

    if request.user.is_authenticated:
        isLoggedIn = True

    cek_timeline(lomba, trainingTL)
    pastTL = cek_timeline_past(trainingTL)

    isActive = False
    today = datetime.date.today()
    if trainingTL.first().start_date <= today <= trainingTL.latest('finish_date').finish_date:
        isActive = True

    args = {
        'lomba': lomba,
        'rules': rules,
        'requirement': requirement,
        'mentors': mentors,
        'learnt': learnt,
        'timeline': trainingTL,
        'pastTL': pastTL,
        'isActive': isActive,
        'isLoggedIn': isLoggedIn
    }
    return render(request, "lomba_detail.html", args)

lomba/templates/lomba.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Lomba
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/lomba.css' %}">
    <script src="{% static 'js/lomba.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            {% for lomba in carousel_lomba %}
                {% if forloop.first %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
                {% else %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}"></li>
                {% endif %}
            {% endfor %}
        </ol>
        <div class="carousel-inner">
            {% for lomba in carousel_lomba %}
                {% if forloop.first %}
                    <div class="carousel-item active">
                {% else %}
                    <div class="carousel-item">
                {% endif %}
                    <div class="kenta-head">
                        <div class="kenta-head-content">
                            <div>
                                {% for k,v in active.items %}
                                    {% if k.nama_lomba == lomba.nama_lomba %}
                                        {% if v %}
                                            <span class="kenta-blurlable">
                                                <span class="dot mr-1"></span>
                                                AIRING NOW!
                                            </span>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}

                                <h1>{{ lomba.alias }}</h1>
                                <h3>{{ lomba.nama_lomba }}</h3>
                                <a href="{% url 'lomba:lomba_detail' lomba.alias %}" class="btn btn-dark">
                                    KNOW MORE!
                                </a>
                            </div>
                        </div>
                        <div class="kenta-head-img">
                            {% if lomba.image %}
                                <img class="d-block w-100" style="object-fit: cover" src="{{ lomba.image.url }}" alt="Lomba Image">
                            {% else %}
                                <img class="d-block w-100" style="object-fit: cover" src="{{ lomba.image_url }}" alt="Lomba Image">
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="kenta-content">
        <h1>Know <br> Now!</h1>
        <div class="card-container">
            {% for lomba in lombaList %}
                <div class="card m-3">
                    {% if lomba.image %}
                        <img class="img-fluid" src="{{ lomba.image.url }}" alt="Card image">
                    {% else %}
                        <img class="img-fluid" src="{{ lomba.image_url }}" alt="Card image">
                    {% endif %}
                    <div class="card-body">
                        <h5>{{ lomba.nama_lomba }}</h5>
                        <div class="card-content mt-4">
                            <div class="card-timeline-now">
                                <span class="dot mr-1"></span>
                                {% for k,v in tlList.items %}
                                    {% if k.nama_lomba == lomba.nama_lomba %}
                                        {% if v == None %}
                                            Tidak ada kegiatan
                                        {% else %}
                                            {{ v.deskripsi }}
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <div class="card-know-more">
                                <a href="{% url 'lomba:lomba_detail' lomba.alias %}">KNOW MORE!</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

lomba/templates/lomba_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ lomba.alias }}
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/lomba.css' %}">
{% endblock %}

{% block content %}
    <div class="kenta-head">
        <div class="kenta-head-content">
            <div>
                {% if isActive %}
                    <span class="kenta-blurlable">
                        <span class="dot mr-1"></span>
                        AIRING NOW!
                    </span>
                {% endif %}
                <h1>{{ lomba.alias }}</h1>
                <h3>{{ lomba.nama_lomba }}</h3>
            </div>
        </div>
        {% if lomba.image %}
            <div class="kenta-head-img"
                 style="background-image: url('{{ lomba.image.url }}')">
            </div>
        {% else %}
            <div class="kenta-head-img"
                 style="background-image: url('{{ lomba.image_url }}')">
            </div>
        {% endif %}
    </div>

    <div class="kenta-content">
        <div>
            {% if lomba.about %}
                <h4>About</h4>
                <p>{{ lomba.about }}</p>

                <hr>
            {% endif %}

            {% if rules %}
                <h4>General Rules</h4>
                <ul>
                    {% for item in rules %}
                        <li>{{ item.rule }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% if requirement %}
                <h4>Participant Requirements</h4>
                <ul>
                    {% for item in requirement %}
                        <li>{{ item.requirement }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% if lomba.guidebook_link %}
                <h4>Guidebook</h4>
                <div class="mt-2 mb-4 d-flex flex-row">
                    <img src="{% static 'svg/guidebook.svg' %}" width="15em" alt="guidebook">
                    <a class="ml-2" href={{ lomba.guidebook_link }}>Get the guidebook here!</a>
                </div>

                <hr>
            {% endif %}

            {% if timeline %}
                <h4>Timeline</h4>
                <div class="kenta-timeline">
                    {% for item in pastTL %}
                        <div class="kenta-timeline-bullet">
                            <svg class="kenta-timeline-past"
                                 width="40" height="59" viewBox="0 0 40 59" fill="yellow"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                      d="M13.7143 21.1965C17.5014 21.1965 20.5715 18.1264 20.5715 14.3393C20.5715 10.5522 17.5014 7.48216 13.7143 7.48216C9.92722 7.48216 6.85716 10.5522 6.85716 14.3393C6.85716 18.1264 9.92722 21.1965 13.7143 21.1965ZM13.7143 28.0536C21.2885 28.0536 27.4286 21.9135 27.4286 14.3393C27.4286 6.76511 21.2885 0.625 13.7143 0.625C6.14011 0.625 0 6.76511 0 14.3393C0 21.9135 6.14011 28.0536 13.7143 28.0536Z"
                                ></path>
                                <path class="kenta-timeline-end" fill-rule="evenodd" clip-rule="evenodd"
                                      d="M13.7142 21.1963C15.6078 21.1963 17.1428 22.7313 17.1428 24.6249V55.4821C17.1428 57.3756 15.6078 58.9107 13.7142 58.9107C11.8207 58.9107 10.2856 57.3756 10.2856 55.4821V24.6249C10.2856 22.7313 11.8207 21.1963 13.7142 21.1963Z"
                                ></path>
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                      d="M20.5713 14.3397C20.5713 12.4462 22.1063 10.9111 23.9999 10.9111H36.5713C38.4649 10.9111 39.9999 12.4462 39.9999 14.3397C39.9999 16.2333 38.4649 17.7683 36.5713 17.7683H23.9999C22.1063 17.7683 20.5713 16.2333 20.5713 14.3397Z"
                                ></path>
                            </svg>
                            <div style="display: flex; flex-direction: column; font-size: large">
                                {% if item.start_date == item.finish_date %}
                                    <span class="kenta-timeline-date">{{ item.start_date|date:"d M Y" }}</span>
                                {% else %}
                                    <span class="kenta-timeline-date">{{ item.start_date|date:"d M Y" }} - {{ item.finish_date|date:"d M Y" }}</span>
                                {% endif %}
                                <span style="font-size: medium">{{ item.deskripsi }}</span>
                            </div>
                        </div>
                    {% endfor %}

                    {% for item in timeline %}
                        {% if item.active == False %}
                        {% else %}
                            <div class="kenta-timeline-bullet">
                                {% if item.active == True %}
                                    <svg class="kenta-timeline-now"
                                         width="40" height="59" viewBox="0 0 40 59" fill="yellow"
                                         xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" clip-rule="evenodd"
                                              d="M13.7143 21.1965C17.5014 21.1965 20.5715 18.1264 20.5715 14.3393C20.5715 10.5522 17.5014 7.48216 13.7143 7.48216C9.92722 7.48216 6.85716 10.5522 6.85716 14.3393C6.85716 18.1264 9.92722 21.1965 13.7143 21.1965ZM13.7143 28.0536C21.2885 28.0536 27.4286 21.9135 27.4286 14.3393C27.4286 6.76511 21.2885 0.625 13.7143 0.625C6.14011 0.625 0 6.76511 0 14.3393C0 21.9135 6.14011 28.0536 13.7143 28.0536Z"
                                        ></path>
                                        <path class="kenta-timeline-end" fill-rule="evenodd" clip-rule="evenodd"
                                              d="M13.7142 21.1963C15.6078 21.1963 17.1428 22.7313 17.1428 24.6249V55.4821C17.1428 57.3756 15.6078 58.9107 13.7142 58.9107C11.8207 58.9107 10.2856 57.3756 10.2856 55.4821V24.6249C10.2856 22.7313 11.8207 21.1963 13.7142 21.1963Z"
                                        ></path>
                                        <path fill-rule="evenodd" clip-rule="evenodd"
                                              d="M20.5713 14.3397C20.5713 12.4462 22.1063 10.9111 23.9999 10.9111H36.5713C38.4649 10.9111 39.9999 12.4462 39.9999 14.3397C39.9999 16.2333 38.4649 17.7683 36.5713 17.7683H23.9999C22.1063 17.7683 20.5713 16.2333 20.5713 14.3397Z"
                                        ></path>
                                    </svg>
                                {% elif item.active == None %}
                                    <svg
                                            width="40" height="59" viewBox="0 0 40 59" fill="yellow"
                                            xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" clip-rule="evenodd"
                                              d="M13.7143 21.1965C17.5014 21.1965 20.5715 18.1264 20.5715 14.3393C20.5715 10.5522 17.5014 7.48216 13.7143 7.48216C9.92722 7.48216 6.85716 10.5522 6.85716 14.3393C6.85716 18.1264 9.92722 21.1965 13.7143 21.1965ZM13.7143 28.0536C21.2885 28.0536 27.4286 21.9135 27.4286 14.3393C27.4286 6.76511 21.2885 0.625 13.7143 0.625C6.14011 0.625 0 6.76511 0 14.3393C0 21.9135 6.14011 28.0536 13.7143 28.0536Z"
                                        ></path>
                                        <path class="kenta-timeline-end" fill-rule="evenodd" clip-rule="evenodd"
                                              d="M13.7142 21.1963C15.6078 21.1963 17.1428 22.7313 17.1428 24.6249V55.4821C17.1428 57.3756 15.6078 58.9107 13.7142 58.9107C11.8207 58.9107 10.2856 57.3756 10.2856 55.4821V24.6249C10.2856 22.7313 11.8207 21.1963 13.7142 21.1963Z"
                                        ></path>
                                        <path fill-rule="evenodd" clip-rule="evenodd"
                                              d="M20.5713 14.3397C20.5713 12.4462 22.1063 10.9111 23.9999 10.9111H36.5713C38.4649 10.9111 39.9999 12.4462 39.9999 14.3397C39.9999 16.2333 38.4649 17.7683 36.5713 17.7683H23.9999C22.1063 17.7683 20.5713 16.2333 20.5713 14.3397Z"
                                        ></path>
                                    </svg>
                                {% endif %}
                                <div style="display: flex; flex-direction: column; font-size: large">
                                    {% if item.start_date == item.finish_date %}
                                    <span class="kenta-timeline-date">{{ item.start_date|date:"d M Y" }}</span>
                                    {% else %}
                                        <span class="kenta-timeline-date">{{ item.start_date|date:"d M Y" }} - {{ item.finish_date|date:"d M Y" }}</span>
                                    {% endif %}
                                    <span style="font-size: medium">{{ item.deskripsi }}</span>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>

    {% if mentors or lomba.start_date or lomba.finish_date or learnt %}
        <div class="kenta-content" style="background-color: #e8f0ff">
            <h1 class="mb-5">Training</h1>
            <div>
                <h4>Mentors</h4>
                {% if mentors %}
                    <ul>
                        {% for mentor in mentors %}
                            <li>{{ mentor }}</li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>To Be Announced</p>
                    <hr>
                {% endif %}

                {% if lomba.start_date and lomba.finish_date %}
                    <h4>Timeline</h4>
                    {% if lomba.alias == 'DAQ' %}
                        <p>{{ lomba.start_date|date:"d M Y" }} - {{ lomba.finish_date|date:"d M Y" }}</p>
                    {% elif lomba.alias == 'MHQ' %}
                        <p>{{ lomba.start_date|date:"d M Y" }} (Saintek) & {{ lomba.finish_date|date:"d M Y" }} (Soshum)</p>
                    {% else %}
                        <p>{{ lomba.start_date|date:"d M Y" }} & {{ lomba.finish_date|date:"d M Y" }}</p>
                    {% endif %}
                {% endif %}

                {% if learnt %}
                    <hr>
                    <h4>You will learn..</h4>
                    <ul>
                        {% for item in learnt %}
                            <li>{{ item.learnt }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
    {% endif %}

    {% if isLoggedIn == True %}
        <div class="text-center mt-4 mb-5">
            <h5>Interested?</h5>
            <a href="{% url 'dashboard:home' %}" class="btn btn-primary mt-2">
                ENROLL VIA
                <br>
                DASHBOARD
            </a>
        </div>
    {% endif %}
{% endblock %}