authentication/urls.py
from django.urls import path
from authentication.views import *

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

dashboard/urls.py
from django.urls import path
from dashboard.views import *

app_name = 'dashboard'

urlpatterns = [
    path('', home, name='home'),
    path('enroll/<int:id_kompetisi>', enroll, name='enroll'),
    path('add/<int:id_kelompok>', add_anggota, name='add_anggota'),
    path('edit/participant/<int:id_peserta>', edit_peserta, name='edit_peserta'),
    path('edit/team/<int:id_kelompok>', edit_kelompok, name='edit_kelompok'),
    path('edit/member/<int:id_anggota>', edit_anggota, name='edit_anggota'),
    path('delete/participant/<int:id_peserta>', delete_peserta, name='delete_peserta'),
    path('delete/team/<int:id_kelompok>', delete_kelompok, name='delete_kelompok'),
    path('delete/member/<int:id_anggota>', delete_anggota, name='delete_anggota'),
    path('view/<int:id_kompetisi>', view_enrollments, name='view_enrollments'),
    path('view/team/<int:id_kelompok>', view_kelompok, name='view_kelompok'),
]

lomba/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "lomba"

urlpatterns = [
    path('', views.lomba_list, name='lomba_list'),
    path('<str:alias>/', views.lomba_detail, name='lomba_detail')
]

mtqui/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('gallery/', include('gallery.urls')),
    path('auth/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('seminar/', include('seminar.urls')),
    path('lomba/', include('lomba.urls')),
    path('admin_mtqui/', include('admin_mtqui.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler400 = "homepage.views.bad_request_view"
handler403 = "homepage.views.permission_denied_view"
handler404 = "homepage.views.page_not_found_view"
handler500 = "homepage.views.server_error_view"

dashboard/views.py
from dashboard.forms import *
from dashboard.models import Anggota, Kelompok, Kompetisi, KompetisiKTIA, Peserta
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

# Create your views here.
@login_required
def home(request):
    if request.user.is_superuser:
        return HttpResponseRedirect("/admin/")

    context = {}

    context["metadata_fakultas"] = request.user.metadata
    context["ktia"] = KompetisiKTIA.objects.all().first()
    context["competitions"] = request.user.kompetisi.all()

    return render(request, "dashboard/dashboard.html", context)


@login_required(redirect_field_name="dashboard:home")
def enroll(request, id_kompetisi):
    kompetisi = get_object_or_404(Kompetisi, id=id_kompetisi)
    
    tipe_kompetisi = kompetisi.get_tipe()

    if (kompetisi.get_owner() != request.user) or (not kompetisi.can_enroll()):
        return redirect(reverse("dashboard:home"))

    if tipe_kompetisi == "Individu":
        return enroll_individu(request, id_kompetisi)

    elif tipe_kompetisi == "Kelompok":
        return enroll_kelompok(request, id_kompetisi)

    elif tipe_kompetisi == "DAQ":
        return enroll_daq(request, id_kompetisi)


def enroll_individu(request, id_kompetisi):
    context = {}

    kompetisi = Kompetisi.objects.get(id=id_kompetisi)

    if request.method == "POST":
        peserta_form = PesertaForm(request.POST, request.FILES)

        if peserta_form.is_valid():
            nama = peserta_form.cleaned_data.get("nama")
            fakultas = request.user.metadata.nama_fakultas
            jurusan = peserta_form.cleaned_data.get("jurusan")
            angkatan = peserta_form.cleaned_data.get("angkatan")
            no_hp = peserta_form.cleaned_data.get("no_hp")
            line_id = peserta_form.cleaned_data.get("line_id")
            foto_ktm = peserta_form.cleaned_data.get("foto_ktm")
            screenshot_siak = peserta_form.cleaned_data.get("screenshot_siak")

            peserta = Peserta(
                        nama=nama, 
                        fakultas=fakultas, 
                        jurusan=jurusan, 
                        angkatan=angkatan, 
                        no_hp=no_hp, 
                        line_id=line_id, 
                        foto_ktm=foto_ktm, 
                        screenshot_siak=screenshot_siak, 
                        kompetisi=kompetisi
                    )
            peserta.save()

            return redirect(reverse("dashboard:view_enrollments", kwargs={'id_kompetisi': kompetisi.id}))

        else:
            context["competition"] = kompetisi
            context["peserta_form"] = peserta_form
            return render(request, "dashboard/enroll_individu.html", context)
    
    context["competition"] = kompetisi
    context["peserta_form"] = PesertaForm()
    return render(request, "dashboard/enroll_individu.html", context)


def enroll_kelompok(request, id_kompetisi):
    context = {}

    kompetisi = Kompetisi.objects.get(id=id_kompetisi)

    if request.method == "POST":
        kelompok_form = KelompokForm(request.POST)
        anggota_form = AnggotaForm(request.POST, request.FILES)

        if kelompok_form.is_valid() and anggota_form.is_valid():
            nama_kelompok = kelompok_form.cleaned_data.get("nama_kelompok")

            kelompok = Kelompok(nama=nama_kelompok, kompetisi=kompetisi)
            kelompok.save()

            nama = anggota_form.cleaned_data.get("nama")
            fakultas = request.user.metadata.nama_fakultas
            jurusan = anggota_form.cleaned_data.get("jurusan")
            angkatan = anggota_form.cleaned_data.get("angkatan")
            no_hp = anggota_form.cleaned_data.get("no_hp")
            line_id = anggota_form.cleaned_data.get("line_id")
            foto_ktm = anggota_form.cleaned_data.get("foto_ktm")
            screenshot_siak = anggota_form.cleaned_data.get("screenshot_siak")

            anggota = Anggota(
                        nama=nama, 
                        fakultas=fakultas, 
                        jurusan=jurusan, 
                        angkatan=angkatan, 
                        no_hp=no_hp, 
                        line_id=line_id, 
                        foto_ktm=foto_ktm, 
                        screenshot_siak=screenshot_siak, 
                        kelompok=kelompok
                    )
            anggota.save()

            return redirect(reverse("dashboard:view_enrollments", kwargs={'id_kompetisi': kompetisi.id}))
    
        else:
            context["competition"] = kompetisi
            context["kelompok_form"] = kelompok_form
            context["anggota_form"] = anggota_form
            return render(request, "dashboard/enroll_kelompok.html", context)
    
    context["competition"] = kompetisi
    context["kelompok_form"] = KelompokForm()
    context["anggota_form"] = AnggotaForm()
    return render(request, "dashboard/enroll_kelompok.html", context)


def enroll_daq(request, id_kompetisi):
    context = {}

    kompetisi = Kompetisi.objects.get(id=id_kompetisi)

    if request.method == "POST":
        anggota_daq_form = AnggotaDAQForm(request.POST, request.FILES)

        if anggota_daq_form.is_valid():
            kelompok = kompetisi.kelompok.all().first()

            if not kelompok:
                nama_kelompok = f"Kelompok DAQ {request.user.metadata.nama_fakultas}"

                kelompok = Kelompok(nama=nama_kelompok, kompetisi=kompetisi)
                kelompok.save()

            nama = anggota_daq_form.cleaned_data.get("nama")
            fakultas = request.user.metadata.nama_fakultas
            jurusan = anggota_daq_form.cleaned_data.get("jurusan")
            angkatan = anggota_daq_form.cleaned_data.get("angkatan")
            no_hp = anggota_daq_form.cleaned_data.get("no_hp")
            line_id = anggota_daq_form.cleaned_data.get("line_id")
            is_ketua = anggota_daq_form.cleaned_data.get("is_ketua")
            foto_ktm = anggota_daq_form.cleaned_data.get("foto_ktm")
            screenshot_siak = anggota_daq_form.cleaned_data.get("screenshot_siak")
            file_cv = anggota_daq_form.cleaned_data.get("file_cv")

            anggota = Anggota(
                        nama=nama,
                        fakultas=fakultas,
                        jurusan=jurusan,
                        angkatan=angkatan,
                        no_hp=no_hp,
                        line_id=line_id,
                        is_ketua=is_ketua,
                        foto_ktm=foto_ktm,
                        screenshot_siak=screenshot_siak,
                        file_cv=file_cv,
                        kelompok=kelompok
                    )
            anggota.save()

            return redirect(reverse("dashboard:view_enrollments", kwargs={'id_kompetisi': kompetisi.id}))

        else:
            context["competition"] = kompetisi
            context["anggota_daq_form"] = anggota_daq_form
            return render(request, "dashboard/enroll_daq.html", context)
    
    context["competition"] = kompetisi
    context["anggota_daq_form"] = AnggotaDAQForm()
    return render(request, "dashboard/enroll_daq.html", context)


@login_required(redirect_field_name="dashboard:home")
def add_anggota(request, id_kelompok):
    kelompok = get_object_or_404(Kelompok, id=id_kelompok)
    tipe_kompetisi = kelompok.get_tipe()

    if (kelompok.get_owner() != request.user) or (not kelompok.can_add_member()):
        return redirect(reverse("dashboard:home"))

    if tipe_kompetisi == "Kelompok":
        return add_anggota_kelompok(request, id_kelompok)

    elif tipe_kompetisi == "DAQ":
        raise PermissionDenied


def add_anggota_kelompok(request, id_kelompok):
    context = {}

    kelompok = Kelompok.objects.get(id=id_kelompok)

    if request.method == "POST":
        anggota_form = AnggotaForm(request.POST, request.FILES)

        if anggota_form.is_valid():
            nama = anggota_form.cleaned_data.get("nama")
            fakultas = request.user.metadata.nama_fakultas
            jurusan = anggota_form.cleaned_data.get("jurusan")
            angkatan = anggota_form.cleaned_data.get("angkatan")
            no_hp = anggota_form.cleaned_data.get("no_hp")
            line_id = anggota_form.cleaned_data.get("line_id")
            foto_ktm = anggota_form.cleaned_data.get("foto_ktm")
            screenshot_siak = anggota_form.cleaned_data.get("screenshot_siak")

            anggota = Anggota(
                        nama=nama, 
                        fakultas=fakultas, 
                        jurusan=jurusan, 
                        angkatan=angkatan, 
                        no_hp=no_hp, 
                        line_id=line_id, 
                        foto_ktm=foto_ktm, 
                        screenshot_siak=screenshot_siak, 
                        kelompok=kelompok
                    )
            anggota.save()

            return redirect(reverse("dashboard:view_kelompok", kwargs={'id_kelompok': kelompok.id}))
        
        else:
            context["kelompok"] = kelompok
            context["anggota_form"] = anggota_form
            return render(request, "dashboard/add_anggota_kelompok.html", context)

    context["kelompok"] = kelompok
    context["anggota_form"] = AnggotaForm()
    return render(request, "dashboard/add_anggota_kelompok.html", context)


@login_required(redirect_field_name="dashboard:home")
def edit_kelompok(request, id_kelompok):
    kelompok = get_object_or_404(Kelompok, id=id_kelompok)
    tipe_kompetisi = kelompok.get_tipe()

    if (kelompok.get_owner() != request.user) or (not kelompok.can_be_edited()):
        return redirect(reverse("dashboard:home"))

    if tipe_kompetisi == "Kelompok":
        return edit_kelompok_biasa(request, id_kelompok)

    elif tipe_kompetisi == "DAQ":

dashboard/templates/dashboard/edit_kelompok_biasa.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Edit - {{ kelompok.nama }}
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'dashboard/css/forms.css' %}">
{% endblock head %}

{% block content %}
<div class="kenta-content">
    <h1>Edit Team</h1>
    <h2>{{ kelompok.kompetisi.judul }}</h2>

    <div class="form-container">
        <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label>Nama Kelompok</label>
                    {{ kelompok_form.nama_kelompok }}

                    {% if kelompok_form.nama_kelompok.errors %}
                    <small class="form-text text-danger form-errors">
                        {% for error in kelompok_form.nama_kelompok.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </small>
                    {% endif %}
                </div>
            </div>

            {% if kelompok_form.non_form_errors %}
            <small class="form-text text-danger">
                {% for error in kelompok_form.non_form_errors %}
                    {{ error|escape }}
                {% endfor %}
            </small>
            {% endif %}

            <br>

            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-success font-weight-bold pt-2 pb-2 pl-4 pr-4">Save Changes</button>
            </div>
        </form>
    </div>
</div>

<script src="{% static 'dashboard/js/invalid_field.js' %}"></script>
<script>
    $(document).ready( () => {
        $("input:text").css("background-color", "#E8F0FF");
        $("input:text").css("border-color", "#51B1F6");

        $("button:submit").css("background-color", "#51B1F6");
        $("button:submit").css("border", "none");
    });
</script>
{% endblock content %}

dashboard/templates/dashboard/view_kelompok.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
View - {{ kelompok.nama }}
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'dashboard/css/enrollment.css' %}">
{% endblock head %}

{% block content %}
<div class="kenta-content">
    <h1>Members</h1>
    <h2>{{ kelompok.nama }}</h2>

    {% for anggota in kelompok.anggota.all %}
    <div class="enrollment-card pt-4 pl-4 pr-4 pb-1">
        <div class="form-row">
            <div class="form-group col-md-12">
                <label>Nama</label>
                <input class="form-control" type="text" placeholder="{{ anggota.nama }}" readonly>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                <label>Fakultas</label>
                <input class="form-control" type="text" placeholder="{{ anggota.fakultas }}" readonly>
            </div>

            <div class="form-group col-md-4">
                <label>Jurusan</label>
                <input class="form-control" type="text" placeholder="{{ anggota.jurusan }}" readonly>
            </div>

            <div class="form-group col-md-4">
                <label>Angkatan</label>
                <input class="form-control" type="text" placeholder="{{ anggota.angkatan }}" readonly>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label>No. HP</label>
                <input class="form-control" type="text" placeholder="{{ anggota.no_hp }}" readonly>
            </div>

            <div class="form-group col-md-6">
                <label>Line ID</label>
                <input class="form-control" type="text" placeholder="{{ anggota.line_id }}" readonly>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label>Foto KTM</label>
                <div class="enrollment-file">
                    <img src="{% static 'dashboard/svg/ktm.svg' %}">
                    <a href="{{ anggota.foto_ktm.url }}" target="_blank">{{ anggota.foto_ktm }}</a>
                </div>
            </div>

            <div class="form-group col-md-6">
                <label>Screenshot SIAK</label>
                <div class="enrollment-file">
                    <img src="{% static 'dashboard/svg/screenshot.svg' %}">
                    <a href="{{ anggota.screenshot_siak.url }}" target="_blank">{{ anggota.screenshot_siak }}</a>
                </div>
            </div>
        </div>

        {% if anggota.can_be_edited %}
        <div>
            <a class="enrollment-button" href="{% url 'dashboard:edit_anggota' id_anggota=anggota.id %}">Edit Member Details</a>
        </div>
        {% endif %}

        {% if anggota.can_be_deleted %}
        <a class="enrollment-button" data-toggle="modal" data-target="#deletionConfirm-{{ anggota.id }}">Remove Member</a>
        
        <div class="modal fade" id="deletionConfirm-{{ anggota.id }}" tabindex="-1" role="dialog" aria-labelledby="deletionConfirmLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deletionConfirmLabel">Are you sure?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        You are about to remove <b>{{ anggota.nama }}</b> from this team.
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <form action="{% url 'dashboard:delete_anggota' id_anggota=anggota.id %}" method="POST"> {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Yes, Remove</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    {% endfor %}

    {% if kelompok.can_add_member %}
    <div class="enrollment-card p-2">
        <div>
            <a class="add-member" href="{% url 'dashboard:add_anggota' id_kelompok=kelompok.id %}">Add Member</a>
        </div>
    </div>
    {% endif %}
</div>

<script>
    $(document).ready( () => {
        $("enrollment-card").css("padding", ".5em");
        $("enrollment-card").css("padding-bottom", ".2em");
        $("enrollment-card").css("margin-bottom", "2em");
        $("enrollment-card").css("border-radius", ".5em");
        $("enrollment-card").css("box-shadow", "0 0 .5em .1em #ddd");
        $("enrollment-card").css("font-weight", "500");

        $("enrollment-button").css("font-weight", "700");

        $("add-member").css("border", "none");
    });
</script>
{% endblock content %}

dashboard/templates/dashboard/view_kompetisi_daq.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
View - {{ competition.judul }}
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'dashboard/css/enrollment.css' %}">
{% endblock head %}

{% block content %}
<div class="kenta-content">
    <h1>Enrollments</h1>
    <h2>{{ competition.judul }}</h2>

    {% for anggota in competition.kelompok.all.first.anggota.all %}
    <div class="enrollment-card pt-4 pl-4 pr-4 pb-1">
        <div class="form-row">
            <div class="form-group col-md-12">
                <label>Nama</label>
                <input class="form-control" type="text" placeholder="{{ anggota.nama }}" readonly>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                <label>Fakultas</label>
                <input class="form-control" type="text" placeholder="{{ anggota.fakultas }}" readonly>
            </div>

            <div class="form-group col-md-4">
                <label>Jurusan</label>
                <input class="form-control" type="text" placeholder="{{ anggota.jurusan }}" readonly>
            </div>

            <div class="form-group col-md-4">
                <label>Angkatan</label>
                <input class="form-control" type="text" placeholder="{{ anggota.angkatan }}" readonly>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label>No. HP</label>
                <input class="form-control" type="text" placeholder="{{ anggota.no_hp }}" readonly>
            </div>

            <div class="form-group col-md-6">
                <label>Line ID</label>
                <input class="form-control" type="text" placeholder="{{ anggota.line_id }}" readonly>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-12">
                <label>Daftar Sebagai</label>
                {% if anggota.is_ketua %}
                <input class="form-control" type="text" placeholder="Ketua" readonly>
                {% else %}
                <input class="form-control" type="text" placeholder="Anggota" readonly>
                {% endif %}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                <label>Foto KTM</label>
                <div class="enrollment-file">
                    <img src="{% static 'dashboard/svg/ktm.svg' %}">
                    <a href="{{ anggota.foto_ktm.url }}" target="_blank">{{ anggota.foto_ktm }}</a>
                </div>
            </div>

            <div class="form-group col-md-4">
                <label>Screenshot SIAK</label>
                <div class="enrollment-file">
                    <img src="{% static 'dashboard/svg/screenshot.svg' %}">
                    <a href="{{ anggota.screenshot_siak.url }}" target="_blank">{{ anggota.screenshot_siak }}</a>
                </div>
            </div>

            <div class="form-group col-md-4">
                <label>Berkas CV</label>
                <div class="enrollment-file">
                    <img src="{% static 'dashboard/svg/cv.svg' %}">
                    <a href="{{ anggota.file_cv.url }}" target="_blank">{{ anggota.file_cv }}</a>
                </div>
            </div>
        </div>

        {% if anggota.can_be_edited %}
        <div>
            <a class="enrollment-button" href="{% url 'dashboard:edit_anggota' id_anggota=anggota.id %}">Edit Enrollment</a>
        </div>
        {% endif %}
        
        {% if anggota.can_be_deleted %}
        <a class="enrollment-button" data-toggle="modal" data-target="#deletionConfirm-{{ anggota.id }}">Remove Participant</a>
        
        <div class="modal fade" id="deletionConfirm-{{ anggota.id }}" tabindex="-1" role="dialog" aria-labelledby="deletionConfirmLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deletionConfirmLabel">Are you sure?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        You are about to remove <b>{{ anggota.nama }}</b> from this competition.
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <form action="{% url 'dashboard:delete_anggota' id_anggota=anggota.id %}" method="POST"> {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Yes, Remove</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    {% endfor %}

    {% if competition.can_enroll %}
    <div class="enrollment-card p-2">
        <div>
            <a class="add-enrollment" href="{% url 'dashboard:enroll' id_kompetisi=competition.id %}">Add Enrollment</a>
        </div>
    </div>
    {% endif %}
</div>

<script>
    $(document).ready( () => {
        $("enrollment-card").css("padding", ".5em");
        $("enrollment-card").css("padding-bottom", ".2em");
        $("enrollment-card").css("margin-bottom", "2em");
        $("enrollment-card").css("border-radius", ".5em");
        $("enrollment-card").css("box-shadow", "0 0 .5em .1em #ddd");
        $("enrollment-card").css("font-weight", "500");

        $("enrollment-button").css("font-weight", "700");
    });
</script>
{% endblock content %}

dashboard/templates/dashboard/view_kompetisi_individu.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
View - {{ competition.judul }}
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'dashboard/css/enrollment.css' %}">
{% endblock head %}

{% block content %}
<div class="kenta-content">
    <h1>Enrollments</h1>
    <h2>{{ competition.judul }}</h2>

    {% for peserta in competition.peserta.all %}
    <div class="enrollment-card pt-4 pl-4 pr-4 pb-1">
        <div class="form-row">
            <div class="form-group col-md-12">
                <label>Nama</label>
                <input class="form-control" type="text" placeholder="{{ peserta.nama }}" readonly>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                <label>Fakultas</label>
                <input class="form-control" type="text" placeholder="{{ peserta.fakultas }}" readonly>
            </div>

            <div class="form-group col-md-4">
                <label>Jurusan</label>
                <input class="form-control" type="text" placeholder="{{ peserta.jurusan }}" readonly>
            </div>

            <div class="form-group col-md-4">
                <label>Angkatan</label>
                <input class="form-control" type="text" placeholder="{{ peserta.angkatan }}" readonly>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label>No. HP</label>
                <input class="form-control" type="text" placeholder="{{ peserta.no_hp }}" readonly>
            </div>

            <div class="form-group col-md-6">
                <label>Line ID</label>
                <input class="form-control" type="text" placeholder="{{ peserta.line_id }}" readonly>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label>Foto KTM</label>
                <div class="enrollment-file">
                    <img src="{% static 'dashboard/svg/ktm.svg' %}">
                    <a href="{{ peserta.foto_ktm.url }}" target="_blank">{{ peserta.foto_ktm }}</a>
                </div>
            </div>

            <div class="form-group col-md-6">
                <label>Screenshot SIAK</label>
                <div class="enrollment-file">
                    <img src="{% static 'dashboard/svg/screenshot.svg' %}">
                    <a href="{{ peserta.screenshot_siak.url }}" target="_blank">{{ peserta.screenshot_siak }}</a>
                </div>
            </div>
        </div>

        {% if peserta.can_be_edited %}
        <div>
            <a class="enrollment-button" href="{% url 'dashboard:edit_peserta' id_peserta=peserta.id %}">Edit Enrollment</a>
        </div>
        {% endif %}
        
        {% if peserta.can_be_deleted %}
        <a class="enrollment-button" data-toggle="modal" data-target="#deletionConfirm-{{ peserta.id }}">Remove Participant</a>
        
        <div class="modal fade" id="deletionConfirm-{{ peserta.id }}" tabindex="-1" role="dialog" aria-labelledby="deletionConfirmLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deletionConfirmLabel">Are you sure?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        You are about to remove <b>{{ peserta.nama }}</b> from this competition.
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <form action="{% url 'dashboard:delete_peserta' id_peserta=peserta.id %}" method="POST"> {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Yes, Remove</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    {% endfor %}

    {% if competition.can_enroll %}
    <div class="enrollment-card p-2">
        <div>
            <a class="add-enrollment" href="{% url 'dashboard:enroll' id_kompetisi=competition.id %}">Add Enrollment</a>
        </div>
    </div>
    {% endif %}
</div>

<script>
    $(document).ready( () => {
        $("enrollment-card").css("padding", ".5em");
        $("enrollment-card").css("padding-bottom", ".2em");
        $("enrollment-card").css("margin-bottom", "2em");
        $("enrollment-card").css("border-radius", ".5em");
        $("enrollment-card").css("box-shadow", "0 0 .5em .1em #ddd");
        $("enrollment-card").css("font-weight", "500");

        $("enrollment-button").css("font-weight", "700");
    });
</script>
{% endblock content %}