authentication/urls.py
from django.urls import path
from authentication.views import *

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

dashboard/urls.py
from django.urls import path
from dashboard.views import *

app_name = 'dashboard'

urlpatterns = [
    path('', home, name='home'),
    path('enroll/<int:id_kompetisi>', enroll, name='enroll'),
    path('add/<int:id_kelompok>', add_anggota, name='add_anggota'),
    path('edit/participant/<int:id_peserta>', edit_peserta, name='edit_peserta'),
    path('edit/team/<int:id_kelompok>', edit_kelompok, name='edit_kelompok'),
    path('edit/member/<int:id_anggota>', edit_anggota, name='edit_anggota'),
    path('delete/participant/<int:id_peserta>', delete_peserta, name='delete_peserta'),
    path('delete/team/<int:id_kelompok>', delete_kelompok, name='delete_kelompok'),
    path('delete/member/<int:id_anggota>', delete_anggota, name='delete_anggota'),
    path('view/<int:id_kompetisi>', view_enrollments, name='view_enrollments'),
    path('view/team/<int:id_kelompok>', view_kelompok, name='view_kelompok'),
]

gallery/urls.py
from django.urls import path
from .views import gallery

app_name = "gallery"

urlpatterns = [
    path('', gallery, name='gallery_home')
]

lomba/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "lomba"

urlpatterns = [
    path('', views.lomba_list, name='lomba_list'),
    path('<str:alias>/', views.lomba_detail, name='lomba_detail')
]

mtqui/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('gallery/', include('gallery.urls')),
    path('auth/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('seminar/', include('seminar.urls')),
    path('lomba/', include('lomba.urls')),
    path('admin_mtqui/', include('admin_mtqui.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler400 = "homepage.views.bad_request_view"
handler403 = "homepage.views.permission_denied_view"
handler404 = "homepage.views.page_not_found_view"
handler500 = "homepage.views.server_error_view"

seminar/urls.py
from django.urls import path
from .views import seminarlanding, getseminar, getseminarform

app_name = "seminar"

urlpatterns = [
    path('', seminarlanding, name='seminar_landing'),
    path('more/<str:id_seminar>/', getseminar, name='get_seminar'),
    path('enroll/', getseminarform, name='get_seminar_form'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/kentastrap.css' %}">
    <script src="{% static 'js/kentastrap.js' %}"></script>
    <title>
        {% block title %}
        {% endblock %}
        | MTQ UI
    </title>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
    <link rel="icon" href="{% static 'img/Rectangle 9.png' %}">
    {% block head %}
    {% endblock %}
</head>
<body>
{% include 'navbar.html' %}
<div class="kenta-main">
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
</div>
</body>
</html>

templates/error.html
{% extends 'base.html' %}
{% block title %}
    Error!
{% endblock %}
{% load static %}
{% block content %}
    <div class="kenta-content">
        <h1>{{ title }}</h1>
        <div class="kenta-abouttext">
            <p>{{ message }}</p>
            <div class="mt-2 mb-4 d-flex flex-row">
                <img src="{% static 'svg/home.svg' %}" width="15em" alt="home">
                <a class="ml-2" href="/">Return to homepage?</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark align-items-center">
    <a class="navbar-brand" href="/">
        <img src="{% static 'img/asset/footer_brand.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""
             style="margin-right: 5px">
        MTQ UI
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
        <ul class="navbar-nav" id="li_nav_container">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home </a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Events
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item disabled">Grand Opening</a>
                    <a class="dropdown-item" href="{% url 'seminar:seminar_landing' %}">Seminar</a>
                    <a class="dropdown-item disabled">Closing Ceremony</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'lomba:lomba_list' %}">Competition</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/guidebook">Guidebook</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gallery:gallery_home' %}">Gallery</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#contacts">Contacts</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item" style="flex-direction: row; justify-content: end; align-items: center">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor"
                     class="bi bi-person-circle" viewBox="0 0 16 16">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
                    <path fill-rule="evenodd"
                          d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"></path>
                </svg>
                <a class="nav-link irfan-nav-link" href="{% url 'dashboard:home' %}"
                   style="display: flex; flex-direction: row; width: 110px; font-size: 0.8rem; line-height: 0.9rem">
                    {{ user.metadata.singkatan_fakultas.upper }} <br>
                    Dashboard
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'authentication:login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>